// Architecture guardrails, checked on the compiled classes of every module by the byterails Maven plugin.
//
// The layout itself comes from the rule sets configured in pom.xml: `kotlin` allows the standard libraries in
// every package, and `hexagonalSpring` declares, under the base package community.flock.examples.axon.webshop,
// the application class and a config package, and in the slice `basket` an isolated domain (domain.model,
// domain.ports, domain.services), an application layer, and the inbound and outbound adapters:
//
//   basket.domain.model                          the model: Basket, Item, Price, Title and the ids; no framework at all
//   basket.domain.ports                          *Port interfaces the application layer needs from the outside
//   basket.application                           the Axon command model, its commands, events, queries and projections
//   basket.adapters.inbound.controllers          the REST controllers implementing the wirespec contract
//   basket.adapters.outbound.database            the JPA read model; its entities in .model, the mappers in .mappers
//
// The rule set's declarations cannot be widened here (declaring one twice is an error), so this file adds what the
// layout does not know about: the libraries this service uses and the packages it has on top of the layout.
byterails {
    // Available to every layer except the isolated domain: the messaging framework, typed errors and coroutines.
    allow("org.axonframework")
    allow("arrow")
    allow("kotlinx.coroutines")

    // Transformer and converter interfaces and the validation problems, shared by the adapters of every slice.
    pkg("common")

    slice {
        allow("common")
        // The HTTP contract, generated by wirespec in the api module, which the controllers implement.
        allow("community.flock.examples.axon.webshop.api")
    }
}
