byterails {
    // Available to every layer except the isolated domain: the messaging framework, typed errors and coroutines.
    allow("org.axonframework")
    allow("arrow")
    allow("kotlinx.coroutines")

    // Transformer and converter interfaces and the validation problems, shared by the adapters of every slice.
    pkg("common")

    slice {
        allow("common")
        // The HTTP contract, generated by wirespec in the api module, which the controllers implement.
        allow("community.flock.examples.axon.webshop.api")
    }
}
