services:
  axon:
    image: axoniq/axonserver:2026.1.2-jdk-21-nonroot
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"

  postgres:
    image: postgres:18 # Also update app/src/test/kotlin/community/flock/examples/axon/webshop/environment/Variables.kt
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: supergebruiker
      POSTGRES_PASSWORD: kapotgeheim
