<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.10</version>
        <relativePath/>
    </parent>

    <groupId>community.flock.examples.axon.webshop</groupId>
    <artifactId>flock-axon-example</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>api</module>
        <module>app</module>
        <module>domain</module>
        <module>spi</module>
    </modules>

    <properties>
        <arrow.version>2.2.3</arrow.version>
        <axon-extensions.version>4.12.0</axon-extensions.version>
        <axon.version>4.9.3</axon.version>
        <java.version>21</java.version>
        <kotest.version>6.2.5</kotest.version>
        <kotlin.version>2.4.20</kotlin.version>
        <ktlint.version>1.8.0</ktlint.version>
        <revision>0.0.1-SNAPSHOT</revision>
        <spotless-ktlint.version>1.8.0</spotless-ktlint.version>
        <spotless-maven-plugin.version>3.9.0</spotless-maven-plugin.version>
        <testcontainers.version>2.0.5</testcontainers.version>
        <wirespec.version>0.21.1</wirespec.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>community.flock.examples.axon.webshop</groupId>
                <artifactId>api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>community.flock.wirespec.integration</groupId>
                <artifactId>spring-jvm</artifactId>
                <version>${wirespec.version}</version>
            </dependency>
            <dependency>
                <groupId>community.flock.wirespec.integration</groupId>
                <artifactId>wirespec-jvm</artifactId>
                <version>${wirespec.version}</version>
            </dependency>
            <dependency>
                <groupId>io.arrow-kt</groupId>
                <artifactId>arrow-core-jvm</artifactId>
                <version>${arrow.version}</version>
            </dependency>
            <dependency>
                <groupId>io.kotest</groupId>
                <artifactId>kotest-assertions-core-jvm</artifactId>
                <version>${kotest.version}</version>
            </dependency>
            <dependency>
                <groupId>org.axonframework</groupId>
                <artifactId>axon-server-connector</artifactId>
                <version>${axon.version}</version>
            </dependency>
            <dependency>
                <groupId>org.axonframework</groupId>
                <artifactId>axon-spring-boot-starter</artifactId>
                <version>${axon.version}</version>
            </dependency>
            <dependency>
                <groupId>org.axonframework</groupId>
                <artifactId>axon-test</artifactId>
                <version>${axon.version}</version>
            </dependency>
            <dependency>
                <groupId>org.axonframework.extensions.kotlin</groupId>
                <artifactId>axon-kotlin</artifactId>
                <version>${axon-extensions.version}</version>
            </dependency>
            <dependency>
                <groupId>org.axonframework.extensions.reactor</groupId>
                <artifactId>axon-reactor-spring-boot-starter</artifactId>
                <version>${axon-extensions.version}</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>${testcontainers.version}</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-junit-jupiter</artifactId>
                <version>${testcontainers.version}</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-postgresql</artifactId>
                <version>${testcontainers.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <extensions>true</extensions>
                    <configuration>
                        <args>
                            <arg>-Xjsr305=strict</arg>
                        </args>
                        <compilerPlugins>
                            <plugin>spring</plugin>
                        </compilerPlugins>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.jetbrains.kotlin</groupId>
                            <artifactId>kotlin-maven-allopen</artifactId>
                            <version>${kotlin.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>community.flock.wirespec.plugin.maven</groupId>
                    <artifactId>wirespec-maven-plugin</artifactId>
                    <version>${wirespec.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>${spotless-maven-plugin.version}</version>
                    <configuration>
                        <kotlin>
                            <includes>
                                <include>src/main/kotlin/**/*.kt</include>
                                <include>src/test/kotlin/**/*.kt</include>
                            </includes>
                            <ktlint>
                                <version>${spotless-ktlint.version}</version>
                                <editorConfigOverride>
                                    <ktlint_code_style>ktlint_official</ktlint_code_style>
                                    <ktlint_standard_multiline-expression-wrapping>disabled</ktlint_standard_multiline-expression-wrapping>
                                    <ktlint_standard_string-template-indent>disabled</ktlint_standard_string-template-indent>
                                    <ktlint_standard_blank-line-between-when-conditions>disabled</ktlint_standard_blank-line-between-when-conditions>
                                    <ktlint_standard_when-entry-bracing>disabled</ktlint_standard_when-entry-bracing>
                                </editorConfigOverride>
                            </ktlint>
                        </kotlin>
                        <pom>
                            <sortPom>
                                <predefinedSortOrder>custom_1</predefinedSortOrder>
                                <lineSeparator>\n</lineSeparator>
                                <encoding>${project.build.sourceEncoding}</encoding>
                                <sortProperties>true</sortProperties>
                                <sortDependencies>scope,groupId,artifactId</sortDependencies>
                                <sortDependencyManagement/>
                                <nrOfIndentSpace>4</nrOfIndentSpace>
                                <expandEmptyElements>false</expandEmptyElements>
                            </sortPom>
                        </pom>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>spotless-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>format</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.diffplug.spotless</groupId>
                            <artifactId>spotless-maven-plugin</artifactId>
                            <configuration>
                                <skip>false</skip>
                            </configuration>
                            <executions>
                                <execution>
                                    <id>spotless-apply</id>
                                    <goals>
                                        <goal>apply</goal>
                                    </goals>
                                    <phase>validate</phase>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

</project>
