spring:
  application:
    name: flock-axon-example
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: supergebruiker
    password: kapotgeheim
  jpa:
    hibernate:
      ddl-auto: update
  web:
    locale: en_US
    locale-resolver: fixed
axon:
  serializer:
    events: jackson
