spring:
  application:
    name: axon-demo
  data:
    mongodb:
      uri: mongodb://localhost:27017/items
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: supergebruiker
    password: kapotgeheim
  web:
    locale: en_US
    locale-resolver: fixed
