import community.flock.byterails.dsl.byterails

byterails {
    // The HTTP contract, generated by wirespec: the endpoints the controllers implement and the
    // models they exchange. Every other module may use those two packages.
    exported("endpoint")
    exported("model")

    // The wirespec runtime and the Spring mapping annotations the generator writes into the endpoints.
    allow("community.flock.wirespec")
    allow("org.springframework.web.bind.annotation")

    pkg("model")
    pkg("endpoint") {
        allow("model")
    }
    pkg("client") {
        allow("endpoint")
        allow("model")
    }
    pkg("generator") {
        allow("model")
    }
}
